"""AI 新闻分类模块的共享契约。"""

MODULE_CONTRACT_VERSION = 2
MODULE_STORAGE_SCHEMA_VERSION = 2

POLICY = "policy"
INDUSTRY = "industry"
RESEARCH = "research"
EXCLUDE = "exclude"

RICE = "rice"
OTHER_CROP = "other_crop"
NOT_APPLICABLE = "not_applicable"

CLASSIFICATION_MODULE_TYPES = frozenset({POLICY, INDUSTRY, RESEARCH, EXCLUDE})
PERSISTED_MODULE_TYPES = frozenset({POLICY, INDUSTRY, RESEARCH})
SPECIES_SCOPE_TYPES = frozenset({RICE, OTHER_CROP, NOT_APPLICABLE})
