"""AI 新闻分类模块的共享契约。"""

MODULE_CONTRACT_VERSION = 3
MODULE_STORAGE_SCHEMA_VERSION = 3

CURRENT_EVENTS = "current_events"
RESEARCH = "research"

RICE = "rice"
OTHER_CROP = "other_crop"
NOT_APPLICABLE = "not_applicable"

CLASSIFICATION_MODULE_TYPES = frozenset({CURRENT_EVENTS, RESEARCH})
PERSISTED_MODULE_TYPES = CLASSIFICATION_MODULE_TYPES
SPECIES_SCOPE_TYPES = frozenset({RICE, OTHER_CROP, NOT_APPLICABLE})
